spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/java2205db?useSSL=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  mvc:
#    static-path-pattern: /static/**
#    path match:
#      matching-strategy: ant_path_matcher
mybatis-plus:
  type-aliases-package: com.example.jwttest.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
page helper:
  helperDialect: mysql
  reasonable: true
server:
  port: 9090